### ISSUE TITLE
Add a flag to save output to a file

### ISSUE THREAD

**Issue by kevin-montrose** [clipperhouse/jargon#7]
Building upon #6 

On some platforms it's a pain to redirect output correctly (for example, .NET's Process isn't super friendly for that), and without significant overhead.  The alternative is having a shell run the actual command, which can also be irritating to do.

Presumably something like `-o <outputfile>`, to go along with `-f`, would solve this.

**Comment by clipperhouse** [comment]
On this branch: https://github.com/clipperhouse/jargon/tree/file-out
